FROM node:18.16.0-alpine as builder
WORKDIR /app
COPY ./package*.json ./
RUN npm i
COPY . .
RUN npm run build

FROM nginx
COPY --from=builder /app/build /usr/share/nginx/html
COPY --from=builder /app/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY /nginx/start.sh /start.sh
RUN chmod +x /start.sh

CMD ["/start.sh"]
