# Generated by Django 5.0.3 on 2024-03-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recognition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognition',
            name='channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
