# Generated by Django 5.0.3 on 2024-03-16 23:15

import api.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recognition_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognition',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Итоги встречи'),
        ),
        migrations.AddField(
            model_name='recognition',
            name='tasks',
            field=models.JSONField(blank=True, null=True, verbose_name='Поручения'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=api.utils.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp4'])], verbose_name='Файл'),
        ),
    ]
