version: "3"
services:
  client:
    # frontend
    stdin_open: true
    build:
      dockerfile: Dockerfile.node
      context: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/staticfiles/:/opt/app/staticfiles/
      - ./backend/media/:/opt/app/media/
  api:
    # backend
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/opt/app/
      - ./backend/media/:/opt/app/media/
      - ./backend/staticfiles/:/opt/app/staticfiles/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - migrations
      # - minio
  db:
    # сервис БД
    image: "postgres:16.2-alpine3.19"
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    shm_size: 128mb
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}" ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
  # minio:
  #   # хранилище S3
  #   image: minio/minio:latest
  #   volumes:
  #     - ./minio_data/:/data
  #   ports:
  #     - "9000:9000"
  #     - "9090:9090"
  #   env_file:
  #     - .env
  #   environment:
  #     MINIO_ACCESS_KEY: ${MINIO_ACCESS}
  #     MINIO_SECRET_KEY: ${SECRET}
  #     MINIO_ROOT_USER: ${MINIO_USER}
  #     MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
  #   command: server --console-address ":9090" /data
  #   healthcheck:
  #     test:
  #       [
  #         "CMD",
  #         "curl",
  #         "-f",
  #         "http://localhost:9000/minio/health/live"
  #       ]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  migrations:
    # миграции django
    build:
      context: ./backend
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate"
    volumes:
      - ./backend/:/opt/app/
      - ./backend/staticfiles/:/opt/app/staticfiles/
    env_file:
      - .env
    depends_on:
      - db
